// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3FZrz0of1DEdku3PI2t8fFNG1f2ZPbLs',
    appId: '1:44270378826:web:bd6028cf326f3d0056abb3',
    messagingSenderId: '44270378826',
    projectId: 'chatapp-e8620',
    authDomain: 'chatapp-e8620.firebaseapp.com',
    storageBucket: 'chatapp-e8620.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAog3yxNFVPybFKVVcNDSWpsIhUzHRwwkk',
    appId: '1:44270378826:android:bd3f2d7f09d974df56abb3',
    messagingSenderId: '44270378826',
    projectId: 'chatapp-e8620',
    storageBucket: 'chatapp-e8620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLFdtyjRHYGa3Fgsv6My5KzsSsGAr0OXw',
    appId: '1:44270378826:ios:9fde72449ef3784156abb3',
    messagingSenderId: '44270378826',
    projectId: 'chatapp-e8620',
    storageBucket: 'chatapp-e8620.appspot.com',
    androidClientId: '44270378826-ib0gbjfubme5hpsr5o1sv2qnne7cck3e.apps.googleusercontent.com',
    iosClientId: '44270378826-gsghqoqnspkmggbuv078urgi0rcd5uo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplicationIubCse464',
  );
}
